articles/urls.py
from django.urls import path
from .views import (
    articlesPage,
    singleArticle,
    editArticle,
)

urlpatterns = [
    path('',articlesPage,name="articles"),
    path('article/<str:pk>/',singleArticle,name="article"),
    path('edit/<str:pk>',editArticle,name='edit'),
]

news/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/",include('userapps.urls')),
    path("",include("articles.urls")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userapps/urls.py
from django.urls import path
from .views import userProfiles,singleProfile,registerUser,loginUser,logoutUser,index

urlpatterns = [ 
    path('profiles/',userProfiles,name="profiles"),
    path('profile<str:pk>/',singleProfile,name="user-profile"),
    path('register/',registerUser,name="register"),
    path("login/",loginUser,name="login"),
    path('logout/',logoutUser,name="logout"),
    path('',index,name="index"),

    
]

articles/models.py
from django.db import models
import uuid
from userapps.models import Profiles

# Create your models here.

class Articles(models.Model):
    owner = models.ForeignKey(Profiles,null=True,on_delete=models.SET_NULL,blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    featured_image = models.ImageField(null=True,blank=True,default="default.jpeg")
    tags = models.ManyToManyField('Tag',blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

    def __str__(self):
        return self.title
    
class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)

    def __str__(self):
         return self.name
    

              

userapps/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.


class Profiles(models.Model):
    id = models.UUIDField(max_length=36,primary_key=True, default=uuid.uuid4, editable=False)
 
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, null=True)
    #profile_image = models.ImageField(
    #    null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    created = models.DateTimeField(auto_now_add=True,null=True)
    
    
    def __str__(self):
        return self.name
    

class Certificates(models.Model):
    description = models.TextField(max_length=50,null=True,blank=True)
    image = models.ImageField(upload_to='profiles/')
    source_link = models.CharField(max_length=200,blank=True,null=True)

    def __str__(self):
        return self.description

  
    
    
class ProfilesName(models.Model):
    pass

articles/forms.py
from .models import Articles
from django.forms import ModelForm


class articleForm(ModelForm):
    class Meta:
        model = Articles
        fields = ['title','description','featured_image','tags']
        

userapps/forms.py
from django.forms import ModelForm
from  django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django import forms
from .models import Profiles


class customUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
        }

    def __init__(self, *args, **kwargs):
        super(customUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class profileForm(forms.ModelForm):
    class Meta:
        model = Profiles
        fields = ['name','description']

articles/views.py
from django.shortcuts import render,redirect
from .models import Articles
from .forms import articleForm
from .utils import searchProjects
from django.contrib import messages
from django.contrib.auth.decorators import login_required



def articlesPage(request):
    projects, search_query = searchProjects(request)
    context = {'articles':projects,'search_query': search_query}
    return render(request, "articles/articles.html",context)

@login_required(login_url="login")
def singleArticle(request, pk):
    singleArt = Articles.objects.get(id=pk)
    context = {"article":singleArt}

    return render(request, 'articles/single_article.html',context)

@login_required(login_url="login")
def editArticle(request,pk):
    article = Articles.objects.get(id=pk)
   
        
    form = articleForm(instance=article)

    if request.method == 'POST':
        form = articleForm(request.POST,request.FILES,instance=article)
        if form.is_valid:
            form.save()
            return redirect("/")
    
    
    context = {'form':form}
    
    return render(request, "articles/article_form.html",context)

userapps/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .forms import customUserCreationForm
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Profiles,Certificates
from articles.models import Articles
from .utils import searchProfiles


# Create your views here.


def userProfiles(request):
    profiles, search_query = searchProfiles(request)
    context = {'profiles':profiles,'search_query': search_query}

    return render(request,"userapps/profiles.html",context)

def singleProfile(request,pk):
    userObj = Profiles.objects.get(id=pk)

    
    context = {"profile":userObj,}


    return render(request, "userapps/single_profile.html",context)

def registerUser(request):
    page = 'register'
    form = customUserCreationForm()

    if request.method == "POST":
        form = customUserCreationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            
            # Check for uniqueness before saving the form
            if User.objects.filter(username=username).exists():
                messages.error(request, 'This username is already in use. Please choose a different one.')
            else:
                try:
                    user = form.save()
                    user.username = user.username.lower()
                    user.save()
                    messages.success(request, 'User account created successfully')
                    login(request, user)
                    return redirect("profiles")
                except:
                    pass

        else:
            messages.error(request, 'An error has occurred while creating the user.')

    context = {'page': page, 'form': form}
    return render(request, "userapps/login_register.html", context)

def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('profiles')


    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'username does not exist or password incorrect')

        user = authenticate(request,username=username, password=password)

        if user is not None:
            login(request,user)
            return redirect('profiles')
        else:
            messages.error(request,"User does not exist")

    return render(request, "userapps/login_register.html")

def logoutUser(request):
    logout(request)
    messages.success(request, 'user logged out succesfully')
    return redirect('login')

def index(request):
    certificates = Certificates.objects.all()

    return render(request, 'userapps/index.html',{'certificates':certificates} )

articles/templates/articles/article_form.html
{%extends 'main.html' %}


{%block content %}
 

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="#"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST" enctype="multipart/form-data" >
                {%csrf_token %}
                <!-- Input:Text -->

                {%for field in form%}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
  
                    
                </div>
                {%endfor %}

                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>



{%endblock content%}

articles/templates/articles/articles.html
{%extends 'main.html'%}


{%block content%}

<main class="projects">
  <section class="hero-section text-center">
    <div class="container container--narrow">
      <div class="hero-section__box">
        <h2>Search for <span>Articles</span></h2>
      </div>

      <div class="hero-section__search">
        <form class="form" action="{%url 'articles' %}" method="get">
          <div class="form__field">
            <label for="formInput#search">Search By Article </label>
            <input class="input input--text" id="formInput#search" type="text" name="search_query"
              placeholder="Search by Title" value="{{search_query}}" />
          </div>

          <input class="btn btn--sub btn--lg" type="submit" value="Search" />
        </form>
      </div>
    </div>
  </section>
  <!-- Search Result: DevList -->
  <section class="projectsList">
    <div class="container">
      <div class="grid grid--three">
        {%for article in articles%}  
        <div class="column">
          <div class="card project">
            <a href="{%url 'article' article.id %}" class="project">
              <img class="project__thumbnail" src="{{article.featured_image.url}}" alt="project thumbnail" />
              <div class="card__body">
                <h3 class="project__title">{{article.title}}</h3>
                <p><a class="project__author" href="{%url 'article' article.id %}">By {{article.owner}} </article></a></p>
                
                <div class="project__tags">
                  {%for tags in article.tags.all%}
                  <span class="tag tag--pill tag--main">
                    <small>{{tags}}</small>
                  </span>
                  {%endfor%}
                 
                </div>
              </div>
            </a>
          </div>
        </div> 
        {%endfor%} 
      </div>
    </div>
  </section>

  
</main>


{%endblock content%}

articles/templates/articles/single_article.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="singleProject my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <h3 class="singleProject__subtitle">Feature</h3>
                <div class="singleProject__toolStack">
                    {% for tag in article.tags.all %}
                    <span class="tag tag--pill tag--sub tag--lg">
                        <small>{{tag}}</small>
                    </span>
                    {% endfor %}

                </div>

                

                

            </div>
            <div class="column column--2of3">
                <img class="singleProject__preview" src="{{ project.imageURL }}" alt="portfolio thumbnail" />
                <a href="#"
                    class="singleProject__developer">{{article.owner.name}}</a>
                <h2 class="singleProject__title">{{article.title}}</h2>
                <h3 class="singleProject__subtitle">About the Project</h3>
                <div class="singleProject__info">
                    {{article.description}}
                </div>
                
            </div>
        </div>
    </div>
    </div>
</main>

{% endblock %}

templates/main.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="{%static 'images/favicon.ico' %}" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="{% static 'uikit/styles/uikit.css' %}" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="{% static 'styles/app.css'%}" />

  <title>NewzCorner</title>
</head>
<body>
    {%include "navbar.html" %}

    

    {%block content %}

    {%endblock content %}

    
</body>
</html>

templates/navbar.html
{% load static %}

<!-- Header Section -->
<header class="header">
    <div class="container container--narrow">
        <a href="{%url 'articles' %}" class="header__logo">
            <img src="{% static 'images/logo.svg' %} " alt="DevSearch Logo" />
        </a>

        <nav class="header__nav">
            <input type="checkbox" id="responsive-menu" />
            <label for="responsive-menu" class="toggle-menu">
                <span>Menu</span>
                <div class="toggle-menu__lines"></div>
            </label>
            <ul class="header__menu">
                <li class="header__menuItem"><a href="{%url 'profiles'%}">Writers</a></li>
                <li class="header__menuItem"><a href="{%url 'articles'%}">Articles</a></li>



                <!--{% if request.user.is_authenticated %}-->
        
                <li class="header__menuItem"><a href="{%url 'logout' %}" class="btn btn--sub">Logout {{user.username}}</a></li>
                <!--{% else %}-->
                <li class="header__menuItem"><a href="{%url 'login' %}" class="btn btn--sub">Login/Sign Up</a></li>
                <!--{% endif %}-->
            </ul>
        </nav>
    </div>
</header> 

templates/projects.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- Favicon -->
  <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
  <!-- Icon - IconMonster -->
  <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
  <!-- Mumble UI -->
  <link rel="stylesheet" href="uikit/styles/uikit.css" />
  <!-- Dev Search UI -->
  <link rel="stylesheet" href="styles/app.css" />

  <title>DevSearch - Connect with Developers!</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header">
    <div class="container container--narrow">
      <a href="/" class="header__logo">
        <img src="images/logo.svg" alt="DevSearch Logo" />
      </a>
      <nav class="header__nav">
        <input type="checkbox" id="responsive-menu" />
        <label for="responsive-menu" class="toggle-menu">
          <span>Menu</span>
          <div class="toggle-menu__lines"></div>
        </label>
        <ul class="header__menu">
          <li class="header__menuItem"><a href="index.html">Developers</a></li>
          <li class="header__menuItem"><a href="projects.html">Projects</a></li>
          <li class="header__menuItem"><a href="inbox.html">Inbox</a></li>
          <li class="header__menuItem"><a href="account.html">My Account</a></li>
          <li class="header__menuItem"><a href="login.html" class="btn btn--sub">Login/Sign Up</a></li>
        </ul>
      </nav>
    </div>
  </header>

  <!-- Main Section -->
  <main class="projects">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>Search for <span>Projects</span></h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search By Projects </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by Project Title" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="projectsList">
      <div class="container">
        <div class="grid grid--three">
          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">98%</span> Postitive
                    Feedback (72 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">DevSearch UI Design</h3>
                  <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">92%</span> Postitive
                    Feedback (62 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Another Landing Page</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">36%</span> Postitive
                    Feedback (18 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-a.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Yoga Studio Landing Page Website and Design</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">98%</span> Postitive
                    Feedback (72 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-b.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">DevSearch UI Design</h3>
                  <p><a class="project__author" href="profile.html">By Shahriar P. Shuvo</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">92%</span> Postitive
                    Feedback (62 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

          <div class="column">
            <div class="card project">
              <a href="single-project.html" class="project">
                <img class="project__thumbnail" src="images/project-c.png" alt="project thumbnail" />
                <div class="card__body">
                  <h3 class="project__title">Another Landing Page</h3>
                  <p><a class="project__author" href="profile.html">By Dennis Ivanov</a></p>
                  <p class="project--rating">
                    <span style="font-weight: bold;">36%</span> Postitive
                    Feedback (18 Votes)
                  </p>
                  <div class="project__tags">
                    <span class="tag tag--pill tag--main">
                      <small>NextJS</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>GraphQL</small>
                    </span>
                    <span class="tag tag--pill tag--main">
                      <small>TypeScript</small>
                    </span>
                  </div>
                </div>
              </a>
            </div>
          </div>

        </div>
      </div>
    </section>

    <div class="pagination">
      <ul class="container">
        <li><a href="#" class="btn btn--disabled">&#10094; Prev</a></li>
        <li><a href="#" class="btn btn--sub">01</a></li>
        <li><a href="#" class="btn">02</a></li>
        <li><a href="#" class="btn">03</a></li>
        <li><a href="#" class="btn">04</a></li>
        <li><a href="#" class="btn">05</a></li>
        <li><a href="#" class="btn">06</a></li>
        <li><a href="#" class="btn">07</a></li>
        <li><a href="#" class="btn">08</a></li>
        <li><a href="#" class="btn">09</a></li>
        <li><a href="#" class="btn">10</a></li>
        <li><a href="#" class="btn">Next &#10095;</a></li>
      </ul>
    </div>
  </main>
</body>

</html>

userapps/templates/userapps/profiles.html
{%extends 'main.html'%}


{%block content%}

<main class="home">
  <section class="hero-section text-center">
      <div class="container container--narrow">
          <div class="hero-section__box">
              <h2>CONNECT WITH <span>Writers</span></h2>
          </div>

          <div class="hero-section__search">

              <form id="searchForm" class="form" action="{% url 'profiles' %}" method="get">
                  <div class="form__field">
                      <label for="formInput#search">Search Writers </label>
                      <input class="input input--text" id="formInput#search" type="text" name="search_query"
                          value="{{search_query}}" placeholder="Search by name" />
                  </div>

                  <input class="btn btn--sub btn--lg" type="submit" value="Search" />
              </form>

          </div>
      </div>
  </section>
  <!-- Search Result: DevList -->
  <section class="devlist">
      <div class="container">
          <div class="grid grid--three">

              {% for profile in profiles %}
              <div class="column card">
                  <div class="dev">
                      <a href="{% url 'user-profile' profile.id %}" class="card__body">
                          <div class="dev__profile">
                              <img class="avatar avatar--md" src="#" alt="image" />
                              <div class="dev__meta">
                                  <h3>{{profile.name}}</h3>
                                  <h5>{{profile.description|slice:"60"}}</h5>
                              </div>
                          </div>
                          <p class="dev__info">{{profile.bio|slice:"150"}}</p>
                          <div class="dev__skills">

                              {% for skill in profile.skill_set.all|slice:"5" %}
                              <span class="tag tag--pill tag--main">
                                  <small>{{skill}}</small>
                              </span>
                              {% endfor %}

                          </div>
                      </a>
                  </div>
              </div>
              {% endfor %}

          </div>
      </div>
  </section>


</main> 

{%endblock content%}

userapps/templates/userapps/single_profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
        <div class="layout">
            <div class="column column--1of3">
                <div class="card text-center">
                    <div class="card__body dev">
                        <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
                        <h2 class="dev__name">{{profile.name}}</h2>
                        <p class="dev__title">{{profile.description}}</p>
                        <p class="dev__location">Based in {{profile.location}}</p>
                        <ul class="dev__social">

                            {% if profile.social_github %}
                            <li>
                                <a title="Github" href="{{profile.social_github}}" target="_blank"><i
                                        class="im im-github"></i></a>
                            </li>
                            {% endif %}


                            {% if profile.social_twitter %}
                            <li>
                                <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i
                                        class="im im-twitter"></i></a>
                            </li>
                            {% endif %}

                            {% if profile.social_linkedin %}
                            <li>
                                <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i
                                        class="im im-linkedin"></i></a>
                            </li>
                            {% endif %}

                            {% if profile.social_website %}
                            <li>
                                <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i
                                        class="im im-globe"></i></a>
                            </li>
                            {% endif %}

                        </ul>
                        {% if request.user.profile.id != profile.id %}
                        <a href="#" class="btn btn--sub btn--lg">Send Message </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="column column--2of3">
                <div class="devInfo">
                    <h3 class="devInfo__title">About Me</h3>
                    <p class="devInfo__about">{{profile.bio}}</p>
                </div>
                
              
                <div class="devInfo">
                    <h3 class="devInfo__title">Articles
                    </h3>
                    <div class="grid grid--two">
                        
                        {%for project in profile.articles_set.all %}
                        <div class="column">
                            <div class="card project">
                                <a href="{% url 'article' project.id %}" class="project">
                                    <img class="project__thumbnail" src="{{project.featured_image.url}}"
                                        alt="project thumbnail" />
                                    <div class="card__body">
                                        <h3 class="project__title">{{project.title}}</h3>
                                        <p><a class="project__author"
                                                href="{% url 'user-profile' project.owner.id %}">By
                                                {{project.owner.name}}</a>
                                        </p>
                                        
                                        
                                        <div class="project__tags">
                                         

                                         

                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                        {%endfor%}   
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

{% endblock content %}